# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food Generator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Food Generator

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

  target 'Food GeneratorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Food GeneratorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
